-- Executar no SQL Editor do Supabase
create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  name text not null,
  attendance text not null check (attendance in ('sim', 'nao')),
  guests integer not null default 0,
  children integer not null default 0,
  guest_names text,
  dietary text,
  transport text,
  message text,
  submitted_at timestamptz not null default now()
);

alter table public.rsvps enable row level security;

-- Permite que convidados submetam respostas usando a anon key.
-- Não permite listar/ler respostas publicamente.
create policy "Public can submit RSVP"
on public.rsvps
for insert
to anon
with check (true);
